apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - talos-default-worker-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-2
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - talos-default-worker-2
